apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullstack-app.fullname" . }}-appdb
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
    {{- include "fullstack-app.appMgmt.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.applicationManagement.hsqldb.storage.storageClassName }}
  storageClassName: {{ .Values.applicationManagement.hsqldb.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.applicationManagement.hsqldb.storage.size }}
