apiVersion: v1
kind: Service
metadata:
  name: application-management-service
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
    {{- include "fullstack-app.appMgmt.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.applicationManagement.service.type }}
  ports:
    - port: {{ .Values.applicationManagement.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack-app.appMgmt.selectorLabels" . | nindent 4 }}
