apiVersion: v1
kind: Service
metadata:
  name: document-management-service
  labels:
    {{- include "uds.labels" . | nindent 4 }}
    {{- include "uds.docMgmt.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.documentManagement.service.type }}
  ports:
    - port: {{ .Values.documentManagement.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uds.docMgmt.selectorLabels" . | nindent 4 }}
